export const SIGN_IN='SIGN_IN';
export const SIGN_OUT='SIGN_OUT';
export const USER_LOADED = "USER_LOADED";
export const FETCH_RECIVEMESSAGES = "FETCH_RECIVEMESSAGES";
export const FETCH_SENTMESSAGES = "FETCH_SENTMESSAGES";
export const FETCH_MESSAGE= "FETCH_MESSAGE";